name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    name: "tests & coverage"
    runs-on: macos-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Lint
      run: ./run-tests.sh -l

    - name: Unit tests
      run: ./run-tests.sh

    - name: Install coverage dependencies
      run: pip install -r requirements-ci.txt

    - name: Codacy
      run: python-codacy-coverage -r coverage.xml -c ${{ github.sha }} || exit 0

    - name: Coveralls
      run: coveralls || exit 0

    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) || exit 0
